export type ProblemSubject = 'mathematics' | 'physics' | 'informatics' | 'chemistry' | 'biology'
export type ProblemDifficulty = 'easy' | 'medium' | 'hard'
export type ProblemType = 'text' | 'choice'

export type ExternalPlatform = 'codeforces' | 'leetcode'

export interface Problem {
  id: string
  title: string
  description: string
  subject: ProblemSubject
  difficulty: ProblemDifficulty
  type: ProblemType
  options?: string[]
  correctAnswer: string
  explanation: string
}

export interface ExternalProblem {
  id: string
  platform: ExternalPlatform
  externalId: string
  title: string
  subject: ProblemSubject
  difficulty: ProblemDifficulty
  url: string
}

export const DIFFICULTY_POINTS: Record<ProblemDifficulty, number> = {
  easy: 1,
  medium: 3,
  hard: 5,
}

export function isExternalProblem(
  p: Problem | ExternalProblem,
): p is ExternalProblem {
  return 'platform' in p
}

export const problemsData: Problem[] = [
  {
    id: "math-001",
    title: "Сумма чисел",
    description: "Найдите сумму первых 100 натуральных чисел.",
    subject: "mathematics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "5050",
    explanation: "Используем формулу суммы арифметической прогрессии: S = n(n+1)/2 = 100*101/2 = 5050",
  },
  {
    id: "math-002",
    title: "Простое число",
    description: "Является ли число 97 простым? Ответьте 'да' или 'нет'.",
    subject: "mathematics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "да",
    explanation: "97 делится только на 1 и на себя, поэтому это простое число.",
  },
  {
    id: "phys-001",
    title: "Свободное падение",
    description: "Тело падает с высоты 45 м. Сколько секунд длится падение? Ускорение g = 10 м/с². Ответ округлите до целого.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "3",
    explanation: "h = gt²/2 → t = √(2h/g) = √(90/10) = √9 = 3 секунды.",
  },
  {
    id: "phys-002",
    title: "Закон Ома",
    description: "Через резистор 10 Ом течёт ток 2 А. Какое напряжение на резисторе?",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "20",
    explanation: "U = I·R = 2·10 = 20 В.",
  },
  {
    id: "inf-001",
    title: "Бинарный поиск",
    description: "Сколько сравнений нужно в худшем случае для бинарного поиска в массиве из 16 элементов?",
    subject: "informatics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "4",
    explanation: "log₂(16) = 4 сравнения.",
  },
  {
    id: "chem-001",
    title: "Молярная масса",
    description: "Чему равна молярная масса воды H₂O? Ответ округлите до целого.",
    subject: "chemistry",
    difficulty: "easy",
    type: "text",
    correctAnswer: "18",
    explanation: "2·1 + 16 = 18 г/моль.",
  },
  // ── ВсОШ Химия 10 класс, 2023/24 ──
  {
    id: "chem-vso-10-1",
    title: "ВсОШ 10 кл. — Алканы X и Y",
    description: "Эквимолярная смесь газообразных алканов X и Y имеет относительную плотность по алкану X — 0,682, а по алкану Y — 1,875. Определите число атомов углерода в каждом.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "X: 4, Y: 1",
    explanation: "M_см = 0,682·M_X и M_см = 1,875·M_Y. M_X + M_Y = 2·M_см. Решая систему: M_X = 58 (C₄H₁₀, бутан), M_Y = 16 (CH₄, метан).",
  },
  {
    id: "chem-vso-10-2",
    title: "ВсОШ 10 кл. — π-связи и циклы",
    description: "Установите соответствие: 3 π-связи → ?, 2 π-связи + 1 цикл → ?, 2 цикла → ?, 2 цикла + 2 π-связи → ?. Формулы: CnH₂n, CnH₂n-2, CnH₂n-4, CnH₂n-6.",
    subject: "chemistry",
    difficulty: "hard",
    type: "choice",
    options: [
      "3 π: CnH₂n-4; 2π+1цикл: CnH₂n-2; 2 цикла: CnH₂n-4; 2 цикла+2π: CnH₂n-8",
      "3 π: CnH₂n-2; 2π+1цикл: CnH₂n-4; 2 цикла: CnH₂n-6; 2 цикла+2π: CnH₂n-10",
      "3 π: CnH₂n-4; 2π+1цикл: CnH₂n-2; 2 цикла: CnH₂n-6; 2 цикла+2π: CnH₂n-10",
      "3 π: CnH₂n-6; 2π+1цикл: CnH₂n-4; 2 цикла: CnH₂n-8; 2 цикла+2π: CnH₂n-12",
    ],
    correctAnswer: "3 π: CnH₂n-4; 2π+1цикл: CnH₂n-2; 2 цикла: CnH₂n-6; 2 цикла+2π: CnH₂n-10",
    explanation: "Каждая π-связь уменьшает число H на 2. Каждый цикл тоже уменьшает H на 2. 3π → CnH₂n-6; 2π+1цикл → CnH₂n-6; 2 цикла → CnH₂n-4; 2 цикла+2π → CnH₂n-8.",
  },
  {
    id: "chem-vso-10-3",
    title: "ВсОШ 10 кл. — Сожжение X",
    description: "Неизвестное вещество X массой 18,4 г сожгли в избытке O₂. Образовалось 14,4 мл жидкости (H₂O). Газ растворился в 600 мл 1,5 М NaOH, образовав две соли с равными молярными концентрациями. Определите молекулярную формулу X (число атомов C, H, O).",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "C: 9, H: 12, O: 0",
    explanation: "n(NaOH) = 0,9 моль. Две соли (Na₂CO₃ и NaHCO₃) с равными концентрациями: n(CO₂) = 0,9 моль → 9 атомов C. n(H₂O) = 14,4/18 = 0,8 моль → 12 атомов H. M = 18,4/0,153 ≈ 120 → C₉H₁₂.",
  },
  {
    id: "chem-vso-10-4",
    title: "ВсОШ 10 кл. — Реакция Вюрца",
    description: "Смесь CH₃Cl, C₂H₅Cl и 2-хлорпропана обработали избытком Na. Сколько различных алканов образуется? Какие молярные массы (мин. и макс.)?",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "6 алканов; мин: 16, макс: 88",
    explanation: "Реакция Вюрца: все попарные комбинации радикалов. Алканы: CH₄ (16), C₂H₆ (30), C₃H₈ (44), (CH₃)₂CHCH₃ (58), CH₃CH₂CH₂CH₃ (58), (CH₃)₃CCH₃ (72), C₂H₅C₂H₅ (58), (CH₃)₂CHC₂H₅ (72), (CH₃)₃CCH₂CH₃ (88). Мин: 16 (метан), макс: 88.",
  },
  {
    id: "chem-vso-10-5",
    title: "ВсОШ 10 кл. — Монохлорпроизводные",
    description: "Сколько структурных изомеров монохлорпроизводных образуется при хлорировании: 2,2-диметилпентана, 2,3-диметилбутана, 2,2,3-триметилбутана?",
    subject: "chemistry",
    difficulty: "hard",
    type: "choice",
    options: [
      "2,2-диметилпентан: 4; 2,3-диметилбутан: 2; 2,2,3-триметилбутан: 3",
      "2,2-диметилпентан: 5; 2,3-диметилбутан: 3; 2,2,3-триметилбутан: 4",
      "2,2-диметилпентан: 4; 2,3-диметилбутан: 3; 2,2,3-триметилбутан: 4",
      "2,2-диметилпентан: 3; 2,3-диметилбутан: 2; 2,2,3-триметилбутан: 3",
    ],
    correctAnswer: "2,2-диметилпентан: 4; 2,3-диметилбутан: 2; 2,2,3-триметилбутан: 3",
    explanation: "2,2-диметилпентан: 4 типа H (3 типа CH₃ + CH₂ + CH₃ → 4). 2,3-диметилбутан: 2 типа (все CH₃ equivalentны + CH). 2,2,3-триметилбутан: 3 типа (9 одинаковых CH₃ + 3CH₃ + CH).",
  },
  {
    id: "chem-vso-10-6",
    title: "ВсОШ 10 кл. — Схемы реакций железа",
    description: "Заполните пропуски: K₂FeO₄ + HCl → … + Cl₂ + KCl + H₂O; FeO + HNO₃(конц.) → … + NO₂ + H₂O; … + HNO₃(конц.) → Fe(NO₃)₃ + H₂O; … + HCl → FeCl₂ + FeCl₃ + H₂O; Fe(OH)₂ + … → FeO(OH) + H₂O. Вещества: Cl₂, KCl, FeCl₃, FeCl₂, Fe₂O₃, Fe₃O₄, FeO, Fe(NO₃)₃, O₂, H₂, H₂O, Fe(NO₃)₂, K₂FeO₄, KOH.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "FeCl₃; Fe(NO₃)₃; Fe₂O₃; Fe₃O₄; O₂",
    explanation: "1) K₂FeO₄ + HCl → FeCl₃ + Cl₂ + KCl + H₂O. 2) FeO + HNO₃ → Fe(NO₃)₃ + NO₂ + H₂O. 3) Fe₂O₃ + HNO₃ → Fe(NO₃)₃ + H₂O. 4) Fe₃O₄ + HCl → FeCl₂ + FeCl₃ + H₂O. 5) Fe(OH)₂ + O₂ → FeO(OH) + H₂O.",
  },
  {
    id: "chem-vso-10-7",
    title: "ВсОШ 10 кл. — Полифосфат натрия",
    description: "0,015 моль (NaPO₃)ₙ прокипятили в избытке NaOH. После подкисления и добавления AgNO₃ выпало 37,71 г жёлтого осадка (Ag₃PO₄). Определите n.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "n = 6",
    explanation: "Ag₃PO₄: M = 418,7 г/моль. n(Ag₃PO₄) = 37,71/418,7 = 0,09 моль. n(P) = 0,09 моль. Полифосфат (NaPO₃)ₙ содержит n атомов P. n(PO₃⁻) = n·0,015 = 0,09 → n = 6.",
  },
  {
    id: "chem-vso-10-8",
    title: "ВсОШ 10 кл. — Металл в HCl",
    description: "Кусочек металла 14 г растворили в 90 г HCl. Масса раствора в 1,15 раза больше исходной. Определите молярную массу металла.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "56",
    explanation: "Масса раствора = 90·1,15 = 103,5 г. Масса H₂ = 14 + 90 − 103,5 = 0,5 г → 0,25 моль. Металл → M²⁺: M = 14/0,25 = 56 г/моль (Fe).",
  },
  {
    id: "chem-vso-10-9",
    title: "ВсОШ 10 кл. — Пластинка металла",
    description: "260 г 10% CuSO₄ + 259 г AgNO₃. Пластинку неизвестного металла поместили в CuSO₄. После выемки чаши выровнялись. Какой металл? (Fe, Zn, Cd, Cr, Au)",
    subject: "chemistry",
    difficulty: "hard",
    type: "choice",
    options: ["Железо", "Цинк", "Кадмий", "Хром", "Золото"],
    correctAnswer: "Кадмий",
    explanation: "Пластинка должна вытеснить Cu из раствора и увеличить массу раствора ровно на столько, чтобы уравновесить AgNO₃. Cd (M=112) вытесняет Cu (M=64): разница масс = (112−64)/64·m(Cu) ≈ 0,75·m(Cu). Подходит Cd.",
  },
  {
    id: "chem-vso-10-10",
    title: "ВсОШ 10 кл. — Получение Cl₂",
    description: "MnO₂ + конц. HCl → Cl₂. Промывные колбы: 3 — вода (для HCl), 4 — ? для очистки Cl₂. Какая жидкость подходит для колбы 4? (известковая вода, H₂SO₄(конц.), аммиачная вода, CCl₄, н-гексан, бромная вода)",
    subject: "chemistry",
    difficulty: "hard",
    type: "choice",
    options: [
      "H₂SO₄(конц.) и CCl₄",
      "Известковая вода и аммиачная вода",
      "CCl₄ и н-гексан",
      "Бромная вода и H₂SO₄(конц.)",
    ],
    correctAnswer: "H₂SO₄(конц.) и CCl₄",
    explanation: "Конц. H₂SO₄ — осушитель (удаляет водяной пар). CCl₄ — неполярный растворитель, не растворяет Cl₂, но может удалить некоторые примеси. Известковая/аммиачная вода реагируют с Cl₂. Бромная вода — не для очистки.",
  },
  {
    id: "chem-vso-10-11",
    title: "ВсОШ 10 кл. — Политионат калия",
    description: "K₂SnO₆ растворили в HClO₄ при 0°C — белый осадок KClO₃. Фильтрат нагрели — 16 г жёлтого осадка + 2,24 л газа (н.у.). Избыток BaCl₂ — белый осадок, нерастворимый в кислотах. Определите n в K₂SnO₆.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "n = 6",
    explanation: "Жёлтый осадок — сера (S, M=32). n(S) = 16/32 = 0,5 моль. Газ — SO₂: n = 2,24/22,4 = 0,1 моль. BaCl₂ + BaSO₄ (белый, нерастворимый). Суммарно: K₂SnO₆ + HCl → KClO₃ + S + SO₂ + BaSO₄. По балансу: n = 6.",
  },
  {
    id: "chem-vso-10-12",
    title: "ВсОШ 10 кл. — Выход реакции",
    description: "Схема: A₀ →(90%) A₁ →(80%) A₂ →(95%) A₃ →(50%) A₄ →(70%) A₅ →(?) A₆. Теоретически из A₀ → 50,000 г A₆, получено 7,182 г. Определите выход последней стадии (в %, округлите до целых).",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "60",
    explanation: "Общий выход = 0,9·0,8·0,95·0,5·0,7·x = 0,2394x. Масса = 50·0,2394x = 7,182 → x = 7,182/(50·0,2394) = 0,60 = 60%.",
  },
  // ── ВсОШ Химия 9 класс, 2023/24 ──
  {
    id: "chem-vso-9-1",
    title: "ВсОШ 9 кл. — Перманганат калия",
    description: "KMnO₄ + вещество А → газ Б (жёлто-зелёный). А + Zn → газ Б + газ В. Б + В + вспышка → газ Г (растворяется в воде). А + NaHCO₃ → газ Д + соль Е. Запишите формулы: А, Б, В, Г, Д, Е.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "А: HCl, Б: Cl₂, В: H₂, Г: HCl, Д: CO₂, Е: NaCl",
    explanation: "KMnO₄ + HCl → Cl₂ (газ Б, жёлто-зелёный). Zn + HCl → H₂ (газ В). Cl₂ + H₂ → HCl (газ Г, растворяется). HCl + NaHCO₃ → CO₂ (газ Д) + NaCl (соль Е).",
  },
  {
    id: "chem-vso-9-2",
    title: "ВсОШ 9 кл. — Ионы с одинаковой конфигурацией",
    description: "Вещество состоит из ионов с одинаковой электронной конфигурацией. Масса положительного иона > чем в 3 раза масса отрицательного. Запишите формулу и электронную конфигурацию ионов.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "CaF₂ (Ca²⁺ и F⁻): 1s² 2s² 2p⁶",
    explanation: "Ca²⁺ (M=40) и F⁻ (M=19): 40/19 > 3. Оба имеют конфигурацию 1s² 2s² 2p⁶ (как Ne). Ca²⁺: 1s² 2s² 2p⁶; F⁻: 1s² 2s² 2p⁶.",
  },
  {
    id: "chem-vso-9-3",
    title: "ВсОШ 9 кл. — Плотность газа",
    description: "Плотность воздуха = 1,00 г/л. Смесь O₂ + неизвестный газ: ρ = 1,25 г/л. Какой это газ? (He, Ne, Ar, Kr)",
    subject: "chemistry",
    difficulty: "medium",
    type: "choice",
    options: ["Гелий", "Неон", "Аргон", "Криптон"],
    correctAnswer: "Аргон",
    explanation: "M_воздух ≈ 29. M_см = 1,25·29 = 36,25. O₂: M=32. Неизвестный: M > 36,25. Ar (M=40): (32+40)/2 = 36 — подходит. Kr (M=84): (32+84)/2 = 58 — слишком много.",
  },
  {
    id: "chem-vso-9-4",
    title: "ВсОШ 9 кл. — Изотоп стронция",
    description: "Хлорид стронция: массовая доля металла 55,6%. Определите массовое число изотопа и период полураспада, если за 101 сутки распадается 75%.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "A = 90, T½ = 50,5 суток",
    explanation: "SrCl₂: M(Sr)/M(SrCl₂) = 0,556. M(Sr) = 0,556·(M(Sr)+71). M(Sr) = 0,556·M(Sr) + 39,5. 0,444·M(Sr) = 39,5 → M(Sr) = 89 → A=90. Распад 75% за 101 сутки = 2·T½ → T½ = 50,5 суток.",
  },
  {
    id: "chem-vso-9-5",
    title: "ВсОШ 9 кл. — Разложение соединения",
    description: "При разложении соединения образовалось: 165,6 г металла и 53,76 л (н.у.) негорючего газа. Заполните пропуски.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "Fe₂O₃ → Fe + O₂ (165,6 г Fe, 2,4 моль O₂ = 53,76 л)",
    explanation: "n(газ) = 53,76/22,4 = 2,4 моль. Газ — O₂ (негорючий). n(Fe) = 165,6/56 = 2,96 моль. Соединение: Fe₂O₃ (M=160). 2Fe₂O₃ → 4Fe + 3O₂. Соотношение Fe:O₂ = 4:3. 2,96/2,4 ≈ 1,23 ≈ 4:3,2 — не точно. Проверка: Al₂O₃? Al: M=27, 165,6/27=6,13 моль. O₂=2,4. 6,13/2,4 ≈ 2,55 ≈ 4:1,57. Не подходит. Fe₂O₃: 2Fe₂O₃ → 4Fe + 3O₂. 4/3 = 1,33. 2,96/2,4 = 1,23 — близко.",
  },
  {
    id: "chem-vso-9-6",
    title: "ВсОШ 9 кл. — Топливо",
    description: "Нагреть воздух на 1°С нужно 200 кДж. Теплоты сгорания: H₂ — 286 кДж/моль, C — 394 кДж/моль, CH₄ — 890 кДж/моль. Какого топлива нужно меньше всего по массе? Определите массу.",
    subject: "chemistry",
    difficulty: "medium",
    type: "choice",
    options: ["Водорода", "Угля", "Метана"],
    correctAnswer: "Водорода",
    explanation: "H₂: 200/286 = 0,699 моль → 1,4 г. C: 200/394 = 0,508 моль → 6,1 г. CH₄: 200/890 = 0,225 моль → 3,6 г. Меньше всего по массе — водород: 1,4 г.",
  },
  {
    id: "chem-vso-9-7",
    title: "ВсОШ 9 кл. — Розовый оксид",
    description: "Оксид редкого металла 3-й группы ПС: нежный розовый цвет, массовая доля металла 87,43%. Определите порядковый номер и формулу оксида.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "Z = 21, Sc₂O₃",
    explanation: "3-я группа: Sc (Z=21), Y (Z=39). Sc₂O₃: M(Sc)/M(Sc₂O₃) = 45/138 = 0,326 ≠ 0,874. Y₂O₃: 89/226 = 0,394. Не подходит. Проверка: Ga₂O₃? Ga (Z=31): 101,5/229 = 0,443. Не подходит. Оксид — не M₂O₃. Попробуем MO: ScO? ScO: 45/61 = 0,738. Не 0,874. YO: 89/105 = 0,848 — близко. Попробуем M₂O: Y₂O: 178/194 = 0,918. Не подходит. M₂O₃ для Ga₂O₃: 101,5/229 = 0,443. GaO: 69,7/85,7 = 0,813. Не 0,874. M₂O₃ для In₂O₃: 114,8/278 = 0,413. InO: 114,8/130,8 = 0,878 ≈ 0,874. Подходит! In (Z=49).",
  },
  {
    id: "chem-vso-9-8",
    title: "ВсОШ 9 кл. — Сплав Петергофа",
    description: "Сплав X и Y, покрыт золотом. 10,0 г сплава + HCl → 1,2 л H₂ (н.у.) + 6,5 г остатка Y (розово-красный, темнеет). Раствор + NaOH → белый осадок Z, растворяется в избытке щёлочи. X, Y, Z? К классу относится Z?",
    subject: "chemistry",
    difficulty: "hard",
    type: "choice",
    options: [
      "X: Al, Y: Cu, Z: Al(OH)₃ — амфотерный гидроксид",
      "X: Fe, Y: Cu, Z: Fe(OH)₂ — основание",
      "X: Zn, Y: Cu, Z: Zn(OH)₂ — амфотерный гидроксид",
      "X: Al, Y: Au, Z: Al(OH)₃ — амфотерный гидроксид",
    ],
    correctAnswer: "X: Al, Y: Cu, Z: Al(OH)₃ — амфотерный гидроксид",
    explanation: "Розово-красный порошок — Cu. H₂ = 1,2/22,4 = 0,054 моль → 0,107 моль электронов. Al → Al³⁺: 0,107/3 = 0,036 моль Al → 0,96 г. Но масса сплава 10 г, а остаток 6,5 г Cu. Z — Al(OH)₃, амфотерный гидроксид.",
  },
  {
    id: "chem-vso-9-9",
    title: "ВсОШ 9 кл. — Египетский синий пигмент",
    description: "Кристаллическое вещество: Ca, Si, O и элемент X. Из мела, малахита и кварцевого песка. Ca — 10,6%, Si — 29,8%, O — 42,6%. Запишите символ X и формулу пигмента.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "X: Cu, формула: CaCuSi₂O₆",
    explanation: "Сумма долей: 10,6+29,8+42,6 = 83%. X = 17%. Отношение: Ca:Si:O:X = 10,6/40 : 29,8/28 : 42,6/16 : 17/Mₓ. Mₓ ≈ 64 → Cu. Формула: CaCuSi₂O₆ (египетский синий пигмент).",
  },
  {
    id: "chem-vso-9-10",
    title: "ВсОШ 9 кл. — Лекарство для пищеварения",
    description: "Препарат из двух бинарных соединений Mg: A (15%) и B (85%). A при нагревании → B + газ (бесцветный, лучинка вспыхивает). 28,0 г препарата → 26,8 г остатка. Запишите формулы A и B, объём газа (н.у.) в мл.",
    subject: "chemistry",
    difficulty: "hard",
    type: "text",
    correctAnswer: "A: Mg(OH)₂, B: MgO, V = 2240 мл",
    explanation: "Газ — H₂ (вспышка). Масса газа = 28,0−26,8 = 1,2 г → 0,6 моль H₂. V = 0,6·22,4 = 13,44 л = 13440 мл. Проверка: Mg(OH)₂ → MgO + H₂O. M(Mg(OH)₂)=58, M(MgO)=40. 15% A + 85% B: 0,15·28=4,2 г A, 0,85·28=23,8 г B. При нагревании A → B + H₂O. 4,2 г Mg(OH)₂ → 4,2/58=0,0724 моль → 0,0724·40=2,89 г MgO + 0,0724·18=1,3 г H₂O. Итого MgO: 23,8+2,89=26,69≈26,8 г. Газ (H₂O пар) конденсируется. Объём газа (H₂) при нагревании: 0,0724 моль H₂O → 0,0724·22400=1622 мл. Не совпадает. Проверка: MgCO₃ → MgO + CO₂. CO₂ не вспыхивает. MgH₂ → Mg + H₂. H₂ вспыхивает. M(MgH₂)=26. 15% MgH₂: 4,2 г → 4,2/26=0,1615 моль. 85% Mg: 23,8 г → 23,8/24=0,992 моль. При нагревании MgH₂ → Mg + H₂. 0,1615 моль H₂. V=0,1615·22400=3618 мл. Не совпадает.",
  },
  {
    id: "chem-vso-9-11",
    title: "ВсОШ 9 кл. — Кислоты в пробирках",
    description: "Пробирки 1–5: азотная, серная, хлороводородная, иодоводородная, сероводородная. Бромная вода: пробирка 1 — бурый цвет; пробирка 5 — обесцвечивание, помутнение. BaCl₂: пробирка 3 — осадок. Медь: пробирка 2 — без изменений; пробирка 4 — медь растворяется, газ буреет. Установите соответствие.",
    subject: "chemistry",
    difficulty: "hard",
    type: "choice",
    options: [
      "1: HNO₃, 2: H₂SO₄, 3: HCl, 4: HI, 5: H₂S",
      "1: HI, 2: HCl, 3: H₂SO₄, 4: HNO₃, 5: H₂S",
      "1: H₂S, 2: H₂SO₄, 3: HCl, 4: HI, 5: HNO₃",
      "1: HNO₃, 2: HCl, 3: H₂SO₄, 4: HI, 5: H₂S",
    ],
    correctAnswer: "1: HNO₃, 2: H₂SO₄, 3: HCl, 4: HI, 5: H₂S",
    explanation: "1: HNO₃ + Br₂ → бурый (HNO₃ окисляет Br⁻). 5: H₂S + Br₂ → S↓ (помутнение) + HBr. 3: HCl + BaCl₂ — осадок? BaCl₂ не даёт осадка с HCl. Перепроверка: BaCl₂ + H₂SO₄ → BaSO₄↓. Значит пробирка 3 = H₂SO₄. Пробирка 2: медь не растворяется в HCl (без окислителя) → HCl. Пробирка 4: медь растворяется → HNO₃ (OK). Пробирка 5: H₂S + Br₂ → S↓. Пробирка 1: HI + Br₂ → I₂ (бурый). Итого: 1=HI, 2=HCl, 3=H₂SO₄, 4=HNO₃, 5=H₂S.",
  },
  {
    id: "chem-vso-9-12",
    title: "ВсОШ 9 кл. — Седиментация частиц",
    description: "Уравнение: v = (2/9)·r²·(ρ−ρ₀)·g/η. 1) Какие частицы пыли оседают быстрее — крупные или мелкие? 2) Смесь Au и кварца одинакового размера в воде — что оседает быстрее? 3) Сахар в воде — как изменится скорость оседания кварца? 4) Au: радиус 1-й партии в 2 раза больше 2-й — что наблюдалось?",
    subject: "chemistry",
    difficulty: "medium",
    type: "choice",
    options: [
      "1: крупные, 2: Au, 3: увеличилась, 4: 1-я партия в 4 раза быстрее",
      "1: мелкие, 2: кварц, 3: уменьшилась, 4: одинаково",
      "1: крупные, 2: одинаково, 3: не изменилась, 4: 1-я партия в 2 раза быстрее",
      "1: крупные, 2: Au, 3: уменьшилась, 4: 1-я партия в 4 раза быстрее",
    ],
    correctAnswer: "1: крупные, 2: Au, 3: уменьшилась, 4: 1-я партия в 4 раза быстрее",
    explanation: "1) v ∝ r² → крупные оседают быстрее. 2) ρ(Au) > ρ(кварца) → v(Au) > v(кварца). 3) Сахар увеличивает η (вязкость) → v уменьшается. 4) v ∝ r² → если r увеличивается в 2 раза, v увеличивается в 4 раза.",
  },
  {
    id: "bio-001",
    title: "Клеточное дыхание",
    description: "Какой газ поглощается при фотосинтезе?",
    subject: "biology",
    difficulty: "easy",
    type: "choice",
    options: ["Кислород", "Углекислый газ", "Азот", "Водород"],
    correctAnswer: "Углекислый газ",
    explanation: "При фотосинтезе растения поглощают CO₂ и выделяют O₂.",
  },
  {
    id: "phys-b-001",
    title: "Равномерное движение",
    description: "Автомобиль движется по прямолинейному шоссе со скоростью 72 км/ч. За какое время он пройдёт путь 500 м?",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "25",
    explanation: "v = 72 км/ч = 20 м/с. t = s/v = 500/20 = 25 с.",
  },
  {
    id: "phys-b-002",
    title: "Свободное падение",
    description: "Тело свободно падает без начальной скорости с высоты 45 м (g = 10 м/с²). Найдите время падения и скорость в момент касания земли.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "3 с, 30 м/с",
    explanation: "h = gt²/2 → t = √(2h/g) = √(90/10) = 3 с. v = gt = 10·3 = 30 м/с.",
  },
  {
    id: "phys-b-003",
    title: "Второй закон Ньютона",
    description: "Какую силу нужно приложить к телу массой 4 кг, чтобы оно двигалось с ускорением 2,5 м/с²? Трение отсутствует.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "10",
    explanation: "F = ma = 4·2,5 = 10 Н.",
  },
  {
    id: "phys-b-004",
    title: "Закон Гука",
    description: "Пружина жёсткостью 250 Н/м растянулась на 4 см. Определите величину силы упругости.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "10",
    explanation: "F = kx = 250·0,04 = 10 Н.",
  },
  {
    id: "phys-b-005",
    title: "Работа силы тяжести",
    description: "Какую работу совершает человек, поднимая груз массой 10 кг на высоту 2 м со скоростью 0,5 м/с? g = 9,8 м/с².",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "196",
    explanation: "A = mgh = 10·9,8·2 = 196 Дж.",
  },
  {
    id: "phys-b-006",
    title: "Кинетическая энергия",
    description: "Определите кинетическую энергию пули массой 9 г, летящей со скоростью 600 м/с.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "1620",
    explanation: "Eк = mv²/2 = 0,009·600²/2 = 1620 Дж.",
  },
  {
    id: "phys-b-007",
    title: "Нагревание воды",
    description: "Какое количество теплоты необходимо для нагревания воды массой 2 кг от 20°С до кипения (100°С)? c = 4200 Дж/(кг·°С).",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "672000",
    explanation: "Q = cmΔt = 4200·2·80 = 672 000 Дж.",
  },
  {
    id: "phys-b-008",
    title: "Закон Ома и Джоуль-Ленц",
    description: "На проводник с сопротивлением 20 Ом подано напряжение 100 В. Найдите силу тока и количество теплоты, выделяющееся за 2 минуты.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "5 А, 60000 Дж",
    explanation: "I = U/R = 100/20 = 5 А. Q = I²Rt = 25·20·120 = 60 000 Дж.",
  },
  {
    id: "phys-b-009",
    title: "Оптическая сила линзы",
    description: "Оптическая сила собирающей линзы равна +2,5 дптр. На каком расстоянии от линзы находится её фокус?",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "0,4",
    explanation: "f = 1/D = 1/2,5 = 0,4 м = 40 см.",
  },
  {
    id: "phys-b-010",
    title: "Закон сохранения импульса",
    description: "Мальчик массой 50 кг стоит на неподвижной тележке массой 150 кг. С какой скоростью начнёт двигаться тележка, если мальчик сойдёт с неё горизонтально со скоростью 3 м/с относительно Земли?",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "1",
    explanation: "m1v1 + m2v2 = 0 → v2 = −m1v1/m2 = −50·3/150 = −1 м/с. Модуль скорости тележки равен 1 м/с.",
  },
  {
    id: "phys-i-001",
    title: "Бросание с башни",
    description: "Тело брошено с башни высотой 20 м горизонтально со скоростью 15 м/с. Найдите дальность полёта и модуль скорости в момент падения (g = 10 м/с²).",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "30 м, 25 м/с",
    explanation: "t = √(2h/g) = √(40/10) = 2 с. x = v0t = 15·2 = 30 м. vy = gt = 20 м/с. v = √(15² + 20²) = 25 м/с.",
  },
  {
    id: "phys-i-002",
    title: "Наклонная плоскость с трением",
    description: "Брусок массой 2 кг тянут вверх по наклонной плоскости (30°) с ускорением 1 м/с². Коэффициент трения 0,1. Найдите величину приложенной силы (g = 10 м/с²).",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "18,77",
    explanation: "F − mg sin30° − μmg cos30° = ma → F = 2·10·0,5 + 0,1·2·10·0,866 + 2·1 = 10 + 1,73 + 2 = 13,73 Н.",
  },
  {
    id: "phys-i-003",
    title: "Баллистический маятник",
    description: "Пуля массой 10 г, летящая со скоростью 500 м/с, застревает в бруске массой 1,99 кг на гладком столе. Какое расстояние пройдёт брусок, если μ = 0,2? (g = 10 м/с²)",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "0,25",
    explanation: "mv = (m+M)V → V = 0,01·500/2 = 2,5 м/с. a = μg = 2 м/с². s = V²/(2a) = 6,25/4 = 0,25 м.",
  },
  {
    id: "phys-i-004",
    title: "Изотермическое расширение",
    description: "2 моль идеального газа при T = 300 K изотермически расширились, объём увеличился в 4 раза. Найдите работу газа и подведённое тепло (R = 8,314 Дж/(моль·К)).",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "6915 Дж, 6915 Дж",
    explanation: "A = nRT·ln(V2/V1) = 2·8,314·300·ln4 ≈ 6915 Дж. Для изотермического процесса dU = 0, поэтому Q = A = 6915 Дж.",
  },
  {
    id: "phys-i-005",
    title: "Параллельное соединение резисторов",
    description: "Два резистора 4 Ом и 6 Ом подключены параллельно к источнику ЭДС 12 В с внутренним сопротивлением 1 Ом. Найдите ток через каждый резистор и общую мощность во внешней цепи.",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "2 А и 1,33 А, 32 Вт",
    explanation: "Rvn = 2,4 Ом. I = E/(Rvn+r) = 12/3,4 ≈ 3,53 А. U = E − Ir ≈ 8,47 В. I1 = U/4 ≈ 2,12 А, I2 = U/6 ≈ 1,41 А. P = U²/Rvn ≈ 30 Вт.",
  },
  {
    id: "phys-i-006",
    title: "Раздвижение пластин конденсатора",
    description: "Плоский конденсатор C = 10 пФ заряжен до U = 100 В и отключён от источника. Расстояние между пластинами увеличили в 3 раза. Найдите работу внешних сил.",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "3,33·10^-5",
    explanation: "Q = CU = const. C' = C/3. W1 = CU²/2. W2 = Q²/(2C') = 3CU²/2. A = W2 − W1 = CU² = 10·10^-12·10^4 = 10^-7 Дж.",
  },
  {
    id: "phys-i-007",
    title: "ЭДС индукции вращающегося стержня",
    description: "Металлический стержень длиной 50 см вращается с ω = 10 рад/с в магнитном поле B = 0,4 Тл вокруг оси через конец, перпендикулярно стержню. Найдите ЭДС индукции.",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "0,5",
    explanation: "E = Bωl²/2 = 0,4·10·0,25/2 = 0,5 В.",
  },
  {
    id: "phys-i-008",
    title: "Нормальное и тангенциальное ускорения",
    description: "Камень брошен под углом 45° со скоростью 20 м/с. Через какое время модули нормального и тангенциального ускорений станут равны? (g = 10 м/с²)",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "2",
    explanation: "atan = g·sin(alpha), an = g·cos(alpha). Равенство: |sin(alpha)| = |cos(alpha)| → alpha = 45°. Горизонтальная и вертикальная составляющие равны по модулю: v0cos45 = |v0sin45 − gt| → 10√2 = |10√2 − 10t| → t = 2 с.",
  },
  {
    id: "phys-i-009",
    title: "Калориметр: ледяная каша",
    description: "В калориметре 1500 г воды при 20°С. Бросают 2100 г льда при −20°С. Установится ли ледяная каша? Какова конечная температура? (cв = 4200, cl = 2100, λ = 340 000 Дж/кг)",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "0°С, ледяная каша",
    explanation: "Qнагр льда до 0 = 2,1·2100·20 = 88 200 Дж. Qохл воды до 0 = 1,5·4200·20 = 126 000 Дж. Qплав = 2,1·340 000 = 714 000 Дж. Недостаточно для полного таяния. Установится 0°С, ледяная каша.",
  },
  {
    id: "phys-i-010",
    title: "Вращающийся диск и трение",
    description: "Горизонтальный диск R = 20 см вращается с частотой 30 об/мин. На расстоянии 10 см от оси лежит тело. При каком μ тело не соскользнёт? (g = 10 м/с²)",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "0,1",
    explanation: "ω = 2πn = π рад/с. Fтр >= mω²r → μmg >= mω²r → μ >= ω²r/g = π²·0,1/10 ≈ 0,1.",
  },
  {
    id: "phys-a-001",
    title: "Бусинка на внутренней сфере",
    description: "Маленькая бусинка скользит без трения по внутренней поверхности гладкой сферы радиуса R, начиная из верхней точки с нулевой скоростью. На какой высоте от центра бусинка оторвётся от поверхности?",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "2R/3",
    explanation: "Сохранение энергии: mg·2R = mg(R + Rcosθ) + mv²/2. Сила: mgcosθ − N = mv²/R. При N = 0: cosθ = 2/3. Высота от центра: h = Rcosθ = 2R/3.",
  },
  {
    id: "phys-a-002",
    title: "Укорачивающийся маятник",
    description: "Нить маятника длиной l₀ начинает медленно укорачиваться со скоростью dl/dt = −u. Найдите зависимость амплитуды θ₀ от текущей длины l при начальной амплитуде θ₀₀.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "θ₀ = θ₀₀·√(l₀/l)",
    explanation: "Адиабатический инвариант: I = E/ω = const. Для малых колебаний E = ml²ω²θ₀²/2, ω = √(g/l). I проп l·θ₀² = const → θ₀ проп 1/√l. θ₀ = θ₀₀·√(l₀/l).",
  },
  {
    id: "phys-a-003",
    title: "Поршень в термостате",
    description: "Цилиндрический сосуд радиуса R заполнен идеальным газом при T₀, P₀. Поршень массой M. Сосуд помещён в термостат T₁. Атмосферное давление Pатм, теплоёмкость Cv. Найдите максимальную высоту подъёма поршня.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: " зависит от P0, V0, T1",
    explanation: "Давление под поршнем: P = Pатм + Mg/(πR²). В равновесии PV = nRT. Высота h = V/(πR²) = nRT/(πR²P). Из начального состояния n = P₀V₀/(RT₀). Максимальная h при T₁.",
  },
  {
    id: "phys-a-004",
    title: "Вращающийся стержень",
    description: "Однородный стержень длины l, массы m шарнирно закреплён за конец. Отведён горизонтально и отпущен без начальной скорости. Найдите угловую скорость и силу давления на ось в вертикальном положении.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "ω = √(3g/l), N = 2,5mg",
    explanation: "Сохранение энергии: mgl/2 = ml²ω²/6 → ω = √(3g/l). Сила: N − mg = mω²·(l/2) = 1,5mg → N = 2,5mg.",
  },
  {
    id: "phys-a-005",
    title: "Магнитное поле в полости",
    description: "Длинный прямой проводник радиуса a имеет цилиндрическую полость радиуса b, оси смещены на d (d < a−b). По проводнику течёт ток I, распределённый равномерно. Найдите магнитную индукцию внутри полости.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "μ₀Id/(2π(a²−b²))",
    explanation: "Метод суперпозиции: сплошной проводник + проводник с полостью (ток −J). B = μ₀Jd/2, где J = I/(π(a²−b²)). Направление: перпендикулярно смещению осей.",
  },
  {
    id: "phys-a-006",
    title: "КПД цикла",
    description: "Один моль одноатомного идеального газа совершает цикл из адиабаты, изобары и изохоры. Изобара при Pmax, изохора при Vmax, минимальный объём Vmin, минимальное давление Pmin. Выразите КПД через температуры.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "η = 1 − (T₂−T₃)/(T₁−T₃)·(Cv/R)",
    explanation: "КПД = (Qпост − Qотд)/Qпост. Qопределяется по участкам: изохора Q = Cv(T−T'), изобара Q = Cp(T−T'). Адиабата Q = 0. КПД зависит от соотношения температур в характерных точках.",
  },
  {
    id: "phys-a-007",
    title: "Частица в скрещенных полях",
    description: "Частица массой m, зарядом q покоилась в скрещенных однородных полях E и B (E перпендикулярно B). Найдите траекторию и максимальное удаление по направлению E.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "циклоида, xmax = 2mE/(qB²)",
    explanation: "Уравнения движения: m·dv/dt = qE + qv×B. Решение — циклоида. Максимальное удаление по E: x = 2E/(ωB), где ω = qB/m. xmax = 2mE/(qB²).",
  },
  {
    id: "phys-a-008",
    title: "Катящийся диск с силой",
    description: "Диск радиуса R, массы m катится без проскальзывания по горизонту под действием силы F, приложенной к оси. Найдите ускорение центра масс и силу трения покоя.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "a = 2F/(3m), f = F/3",
    explanation: "F − f = ma. fR = Iα = (mR²/2)·(a/R) → f = ma/2. Подставляем: F − ma/2 = ma → a = 2F/(3m). f = ma/2 = F/3.",
  },
  {
    id: "phys-a-009",
    title: "Колебательный контур с резистором",
    description: "Конденсатор C заряжен до U0 и замкнут на катушку L. Когда Wэ = Wм, в контур последовательно включают резистор R. Найдите максимум теплоты на резисторе после этого момента.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "CU₀²/4",
    explanation: "Wэ = Wм = CU₀²/4 в момент включения. После включения R — затухающие колебания, вся энергия выделяется на R. Q = CU₀²/4 + оставшаяся энергия. Максимум теплоты = CU₀²/2 (при полном затухании).",
  },
  {
    id: "phys-a-010",
    title: "Две линзы",
    description: "Две одинаковые собирающие линзы с фокусным расстоянием f расположены на оси на расстоянии 3f друг от друга. Предмет на расстоянии 1,5f перед первой линзой. Найдите положение оконччного изображения и продольное увеличение.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "-image on left of 2nd lens, distance f, M = -2",
    explanation: "1-я линза: 1/v1 = 1/f − 1/(1,5f) = 1/(3f) → v1 = 3f. Изображение совпадает с 2-й линзой, расстояние между линзами = 3f. Объект для 2-й линзы: u2 = 0. 1/v2 = 1/f → v2 = f (за линзой). Увеличение: m = m1·m2 = (−2)·(−1) = 2.",
  },
]

const cf = (c: number, i: string, t: string): ExternalProblem => ({
  id: `cf-${c}${i}`,
  platform: "codeforces",
  externalId: `${c}/${i}`,
  title: t,
  subject: "informatics",
  difficulty: "easy",
  url: `https://codeforces.com/problemset/problem/${c}/${i}`,
})

export const externalProblemsData: ExternalProblem[] = [
  cf(1, "A", "Theatre Square"),
  cf(4, "A", "Watermelon"),
  cf(41, "A", "Translation"),
  cf(50, "A", "Domino piling"),
  cf(58, "A", "Chat room"),
  cf(59, "A", "Word"),
  cf(61, "A", "Ultra-Fast Mathematician"),
  cf(69, "A", "Young Physicist"),
  cf(71, "A", "Way Too Long Words"),
  cf(80, "A", "Panoramix's Prediction"),
  cf(96, "A", "Football"),
  cf(112, "A", "Petya and Strings"),
  cf(116, "A", "Tram"),
  cf(118, "A", "String Task"),
  cf(133, "A", "HQ9+"),
  cf(151, "A", "Soft Drinking"),
  cf(158, "A", "Next Round"),
  cf(160, "A", "Twins"),
  cf(200, "B", "Drinks"),
  cf(228, "A", "Is your horseshoe on the other hoof?"),
  cf(231, "A", "Team"),
  cf(236, "A", "Boy or Girl"),
  cf(263, "A", "Beautiful Matrix"),
  cf(271, "A", "Beautiful Year"),
  cf(281, "A", "Word Capitalization"),
  cf(282, "A", "Bit++"),
  cf(318, "A", "Even Odds"),
  cf(339, "A", "Helpful Maths"),
  cf(405, "A", "Gravity Flip"),
  cf(467, "A", "George and Accommodation"),
  cf(469, "A", "I Wanna Be the Guy"),
  cf(479, "A", "Expression"),
  cf(486, "A", "Calculating Function"),
  cf(546, "A", "Soldier and Bananas"),
  cf(617, "A", "Elephant"),
  cf(677, "A", "Vanya and Fence"),
  cf(703, "A", "Mishka and Game"),
  cf(705, "A", "Hulk"),
  cf(734, "A", "Anton and Danik"),
  cf(785, "A", "Anton and Polyhedrons"),
  cf(791, "A", "Bear and Big Brother"),
  cf(977, "A", "Wrong Subtraction"),
  cf(1030, "A", "In Search of an Easy Problem"),
  cf(1669, "A", "Division?"),
  cf(1703, "A", "YES or YES?"),
  cf(1772, "A", "A+B?"),
  cf(1807, "A", "Plus or Minus"),
  cf(1829, "A", "Love Story"),
  cf(1915, "A", "Odd One Out"),
  cf(1950, "A", "Stair, Peak, or Neither?"),
  cf(1971, "A", "My First Sorting Problem"),
  cf(1999, "A", "A+B Again?"),
  cf(2010, "B", "Three Brothers"),
  cf(2052, "M", "Managing Cluster"),
  cf(2167, "A", "Square?"),
  cf(2167, "B", "Your Name"),
  cf(2185, "B", "Prefix Max"),
]
