export type ProblemSubject = 'mathematics' | 'physics' | 'informatics' | 'chemistry' | 'biology'
export type ProblemDifficulty = 'easy' | 'medium' | 'hard'
export type ProblemType = 'text' | 'choice'

export type ExternalPlatform = 'codeforces' | 'leetcode'

export interface Problem {
  id: string
  title: string
  description: string
  subject: ProblemSubject
  difficulty: ProblemDifficulty
  type: ProblemType
  options?: string[]
  correctAnswer: string
  explanation: string
}

export interface ExternalProblem {
  id: string
  platform: ExternalPlatform
  externalId: string
  title: string
  subject: ProblemSubject
  difficulty: ProblemDifficulty
  url: string
}

export const DIFFICULTY_POINTS: Record<ProblemDifficulty, number> = {
  easy: 1,
  medium: 3,
  hard: 5,
}

export function isExternalProblem(
  p: Problem | ExternalProblem,
): p is ExternalProblem {
  return 'platform' in p
}

export const problemsData: Problem[] = [
  {
    id: "math-001",
    title: "Сумма чисел",
    description: "Найдите сумму первых 100 натуральных чисел.",
    subject: "mathematics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "5050",
    explanation: "Используем формулу суммы арифметической прогрессии: S = n(n+1)/2 = 100*101/2 = 5050",
  },
  {
    id: "math-002",
    title: "Простое число",
    description: "Является ли число 97 простым? Ответьте 'да' или 'нет'.",
    subject: "mathematics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "да",
    explanation: "97 делится только на 1 и на себя, поэтому это простое число.",
  },
  {
    id: "phys-001",
    title: "Свободное падение",
    description: "Тело падает с высоты 45 м. Сколько секунд длится падение? Ускорение g = 10 м/с². Ответ округлите до целого.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "3",
    explanation: "h = gt²/2 → t = √(2h/g) = √(90/10) = √9 = 3 секунды.",
  },
  {
    id: "phys-002",
    title: "Закон Ома",
    description: "Через резистор 10 Ом течёт ток 2 А. Какое напряжение на резисторе?",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "20",
    explanation: "U = I·R = 2·10 = 20 В.",
  },
  {
    id: "inf-001",
    title: "Бинарный поиск",
    description: "Сколько сравнений нужно в худшем случае для бинарного поиска в массиве из 16 элементов?",
    subject: "informatics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "4",
    explanation: "log₂(16) = 4 сравнения.",
  },
  {
    id: "chem-001",
    title: "Молярная масса",
    description: "Чему равна молярная масса воды H₂O? Ответ округлите до целого.",
    subject: "chemistry",
    difficulty: "easy",
    type: "text",
    correctAnswer: "18",
    explanation: "2·1 + 16 = 18 г/моль.",
  },
  {
    id: "bio-001",
    title: "Клеточное дыхание",
    description: "Какой газ поглощается при фотосинтезе?",
    subject: "biology",
    difficulty: "easy",
    type: "choice",
    options: ["Кислород", "Углекислый газ", "Азот", "Водород"],
    correctAnswer: "Углекислый газ",
    explanation: "При фотосинтезе растения поглощают CO₂ и выделяют O₂.",
  },
  {
    id: "phys-b-001",
    title: "Равномерное движение",
    description: "Автомобиль движется по прямолинейному шоссе со скоростью 72 км/ч. За какое время он пройдёт путь 500 м?",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "25",
    explanation: "v = 72 км/ч = 20 м/с. t = s/v = 500/20 = 25 с.",
  },
  {
    id: "phys-b-002",
    title: "Свободное падение",
    description: "Тело свободно падает без начальной скорости с высоты 45 м (g = 10 м/с²). Найдите время падения и скорость в момент касания земли.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "3 с, 30 м/с",
    explanation: "h = gt²/2 → t = √(2h/g) = √(90/10) = 3 с. v = gt = 10·3 = 30 м/с.",
  },
  {
    id: "phys-b-003",
    title: "Второй закон Ньютона",
    description: "Какую силу нужно приложить к телу массой 4 кг, чтобы оно двигалось с ускорением 2,5 м/с²? Трение отсутствует.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "10",
    explanation: "F = ma = 4·2,5 = 10 Н.",
  },
  {
    id: "phys-b-004",
    title: "Закон Гука",
    description: "Пружина жёсткостью 250 Н/м растянулась на 4 см. Определите величину силы упругости.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "10",
    explanation: "F = kx = 250·0,04 = 10 Н.",
  },
  {
    id: "phys-b-005",
    title: "Работа силы тяжести",
    description: "Какую работу совершает человек, поднимая груз массой 10 кг на высоту 2 м со скоростью 0,5 м/с? g = 9,8 м/с².",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "196",
    explanation: "A = mgh = 10·9,8·2 = 196 Дж.",
  },
  {
    id: "phys-b-006",
    title: "Кинетическая энергия",
    description: "Определите кинетическую энергию пули массой 9 г, летящей со скоростью 600 м/с.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "1620",
    explanation: "Eк = mv²/2 = 0,009·600²/2 = 1620 Дж.",
  },
  {
    id: "phys-b-007",
    title: "Нагревание воды",
    description: "Какое количество теплоты необходимо для нагревания воды массой 2 кг от 20°С до кипения (100°С)? c = 4200 Дж/(кг·°С).",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "672000",
    explanation: "Q = cmΔt = 4200·2·80 = 672 000 Дж.",
  },
  {
    id: "phys-b-008",
    title: "Закон Ома и Джоуль-Ленц",
    description: "На проводник с сопротивлением 20 Ом подано напряжение 100 В. Найдите силу тока и количество теплоты, выделяющееся за 2 минуты.",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "5 А, 60000 Дж",
    explanation: "I = U/R = 100/20 = 5 А. Q = I²Rt = 25·20·120 = 60 000 Дж.",
  },
  {
    id: "phys-b-009",
    title: "Оптическая сила линзы",
    description: "Оптическая сила собирающей линзы равна +2,5 дптр. На каком расстоянии от линзы находится её фокус?",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "0,4",
    explanation: "f = 1/D = 1/2,5 = 0,4 м = 40 см.",
  },
  {
    id: "phys-b-010",
    title: "Закон сохранения импульса",
    description: "Мальчик массой 50 кг стоит на неподвижной тележке массой 150 кг. С какой скоростью начнёт двигаться тележка, если мальчик сойдёт с неё горизонтально со скоростью 3 м/с относительно Земли?",
    subject: "physics",
    difficulty: "easy",
    type: "text",
    correctAnswer: "1",
    explanation: "m1v1 + m2v2 = 0 → v2 = −m1v1/m2 = −50·3/150 = −1 м/с. Модуль скорости тележки равен 1 м/с.",
  },
  {
    id: "phys-i-001",
    title: "Бросание с башни",
    description: "Тело брошено с башни высотой 20 м горизонтально со скоростью 15 м/с. Найдите дальность полёта и модуль скорости в момент падения (g = 10 м/с²).",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "30 м, 25 м/с",
    explanation: "t = √(2h/g) = √(40/10) = 2 с. x = v0t = 15·2 = 30 м. vy = gt = 20 м/с. v = √(15² + 20²) = 25 м/с.",
  },
  {
    id: "phys-i-002",
    title: "Наклонная плоскость с трением",
    description: "Брусок массой 2 кг тянут вверх по наклонной плоскости (30°) с ускорением 1 м/с². Коэффициент трения 0,1. Найдите величину приложенной силы (g = 10 м/с²).",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "18,77",
    explanation: "F − mg sin30° − μmg cos30° = ma → F = 2·10·0,5 + 0,1·2·10·0,866 + 2·1 = 10 + 1,73 + 2 = 13,73 Н.",
  },
  {
    id: "phys-i-003",
    title: "Баллистический маятник",
    description: "Пуля массой 10 г, летящая со скоростью 500 м/с, застревает в бруске массой 1,99 кг на гладком столе. Какое расстояние пройдёт брусок, если μ = 0,2? (g = 10 м/с²)",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "0,25",
    explanation: "mv = (m+M)V → V = 0,01·500/2 = 2,5 м/с. a = μg = 2 м/с². s = V²/(2a) = 6,25/4 = 0,25 м.",
  },
  {
    id: "phys-i-004",
    title: "Изотермическое расширение",
    description: "2 моль идеального газа при T = 300 K изотермически расширились, объём увеличился в 4 раза. Найдите работу газа и подведённое тепло (R = 8,314 Дж/(моль·К)).",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "6915 Дж, 6915 Дж",
    explanation: "A = nRT·ln(V2/V1) = 2·8,314·300·ln4 ≈ 6915 Дж. Для изотермического процесса dU = 0, поэтому Q = A = 6915 Дж.",
  },
  {
    id: "phys-i-005",
    title: "Параллельное соединение резисторов",
    description: "Два резистора 4 Ом и 6 Ом подключены параллельно к источнику ЭДС 12 В с внутренним сопротивлением 1 Ом. Найдите ток через каждый резистор и общую мощность во внешней цепи.",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "2 А и 1,33 А, 32 Вт",
    explanation: "Rvn = 2,4 Ом. I = E/(Rvn+r) = 12/3,4 ≈ 3,53 А. U = E − Ir ≈ 8,47 В. I1 = U/4 ≈ 2,12 А, I2 = U/6 ≈ 1,41 А. P = U²/Rvn ≈ 30 Вт.",
  },
  {
    id: "phys-i-006",
    title: "Раздвижение пластин конденсатора",
    description: "Плоский конденсатор C = 10 пФ заряжен до U = 100 В и отключён от источника. Расстояние между пластинами увеличили в 3 раза. Найдите работу внешних сил.",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "3,33·10^-5",
    explanation: "Q = CU = const. C' = C/3. W1 = CU²/2. W2 = Q²/(2C') = 3CU²/2. A = W2 − W1 = CU² = 10·10^-12·10^4 = 10^-7 Дж.",
  },
  {
    id: "phys-i-007",
    title: "ЭДС индукции вращающегося стержня",
    description: "Металлический стержень длиной 50 см вращается с ω = 10 рад/с в магнитном поле B = 0,4 Тл вокруг оси через конец, перпендикулярно стержню. Найдите ЭДС индукции.",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "0,5",
    explanation: "E = Bωl²/2 = 0,4·10·0,25/2 = 0,5 В.",
  },
  {
    id: "phys-i-008",
    title: "Нормальное и тангенциальное ускорения",
    description: "Камень брошен под углом 45° со скоростью 20 м/с. Через какое время модули нормального и тангенциального ускорений станут равны? (g = 10 м/с²)",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "2",
    explanation: "atan = g·sin(alpha), an = g·cos(alpha). Равенство: |sin(alpha)| = |cos(alpha)| → alpha = 45°. Горизонтальная и вертикальная составляющие равны по модулю: v0cos45 = |v0sin45 − gt| → 10√2 = |10√2 − 10t| → t = 2 с.",
  },
  {
    id: "phys-i-009",
    title: "Калориметр: ледяная каша",
    description: "В калориметре 1500 г воды при 20°С. Бросают 2100 г льда при −20°С. Установится ли ледяная каша? Какова конечная температура? (cв = 4200, cl = 2100, λ = 340 000 Дж/кг)",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "0°С, ледяная каша",
    explanation: "Qнагр льда до 0 = 2,1·2100·20 = 88 200 Дж. Qохл воды до 0 = 1,5·4200·20 = 126 000 Дж. Qплав = 2,1·340 000 = 714 000 Дж. Недостаточно для полного таяния. Установится 0°С, ледяная каша.",
  },
  {
    id: "phys-i-010",
    title: "Вращающийся диск и трение",
    description: "Горизонтальный диск R = 20 см вращается с частотой 30 об/мин. На расстоянии 10 см от оси лежит тело. При каком μ тело не соскользнёт? (g = 10 м/с²)",
    subject: "physics",
    difficulty: "medium",
    type: "text",
    correctAnswer: "0,1",
    explanation: "ω = 2πn = π рад/с. Fтр >= mω²r → μmg >= mω²r → μ >= ω²r/g = π²·0,1/10 ≈ 0,1.",
  },
  {
    id: "phys-a-001",
    title: "Бусинка на внутренней сфере",
    description: "Маленькая бусинка скользит без трения по внутренней поверхности гладкой сферы радиуса R, начиная из верхней точки с нулевой скоростью. На какой высоте от центра бусинка оторвётся от поверхности?",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "2R/3",
    explanation: "Сохранение энергии: mg·2R = mg(R + Rcosθ) + mv²/2. Сила: mgcosθ − N = mv²/R. При N = 0: cosθ = 2/3. Высота от центра: h = Rcosθ = 2R/3.",
  },
  {
    id: "phys-a-002",
    title: "Укорачивающийся маятник",
    description: "Нить маятника длиной l₀ начинает медленно укорачиваться со скоростью dl/dt = −u. Найдите зависимость амплитуды θ₀ от текущей длины l при начальной амплитуде θ₀₀.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "θ₀ = θ₀₀·√(l₀/l)",
    explanation: "Адиабатический инвариант: I = E/ω = const. Для малых колебаний E = ml²ω²θ₀²/2, ω = √(g/l). I проп l·θ₀² = const → θ₀ проп 1/√l. θ₀ = θ₀₀·√(l₀/l).",
  },
  {
    id: "phys-a-003",
    title: "Поршень в термостате",
    description: "Цилиндрический сосуд радиуса R заполнен идеальным газом при T₀, P₀. Поршень массой M. Сосуд помещён в термостат T₁. Атмосферное давление Pатм, теплоёмкость Cv. Найдите максимальную высоту подъёма поршня.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: " зависит от P0, V0, T1",
    explanation: "Давление под поршнем: P = Pатм + Mg/(πR²). В равновесии PV = nRT. Высота h = V/(πR²) = nRT/(πR²P). Из начального состояния n = P₀V₀/(RT₀). Максимальная h при T₁.",
  },
  {
    id: "phys-a-004",
    title: "Вращающийся стержень",
    description: "Однородный стержень длины l, массы m шарнирно закреплён за конец. Отведён горизонтально и отпущен без начальной скорости. Найдите угловую скорость и силу давления на ось в вертикальном положении.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "ω = √(3g/l), N = 2,5mg",
    explanation: "Сохранение энергии: mgl/2 = ml²ω²/6 → ω = √(3g/l). Сила: N − mg = mω²·(l/2) = 1,5mg → N = 2,5mg.",
  },
  {
    id: "phys-a-005",
    title: "Магнитное поле в полости",
    description: "Длинный прямой проводник радиуса a имеет цилиндрическую полость радиуса b, оси смещены на d (d < a−b). По проводнику течёт ток I, распределённый равномерно. Найдите магнитную индукцию внутри полости.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "μ₀Id/(2π(a²−b²))",
    explanation: "Метод суперпозиции: сплошной проводник + проводник с полостью (ток −J). B = μ₀Jd/2, где J = I/(π(a²−b²)). Направление: перпендикулярно смещению осей.",
  },
  {
    id: "phys-a-006",
    title: "КПД цикла",
    description: "Один моль одноатомного идеального газа совершает цикл из адиабаты, изобары и изохоры. Изобара при Pmax, изохора при Vmax, минимальный объём Vmin, минимальное давление Pmin. Выразите КПД через температуры.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "η = 1 − (T₂−T₃)/(T₁−T₃)·(Cv/R)",
    explanation: "КПД = (Qпост − Qотд)/Qпост. Qопределяется по участкам: изохора Q = Cv(T−T'), изобара Q = Cp(T−T'). Адиабата Q = 0. КПД зависит от соотношения температур в характерных точках.",
  },
  {
    id: "phys-a-007",
    title: "Частица в скрещенных полях",
    description: "Частица массой m, зарядом q покоилась в скрещенных однородных полях E и B (E перпендикулярно B). Найдите траекторию и максимальное удаление по направлению E.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "циклоида, xmax = 2mE/(qB²)",
    explanation: "Уравнения движения: m·dv/dt = qE + qv×B. Решение — циклоида. Максимальное удаление по E: x = 2E/(ωB), где ω = qB/m. xmax = 2mE/(qB²).",
  },
  {
    id: "phys-a-008",
    title: "Катящийся диск с силой",
    description: "Диск радиуса R, массы m катится без проскальзывания по горизонту под действием силы F, приложенной к оси. Найдите ускорение центра масс и силу трения покоя.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "a = 2F/(3m), f = F/3",
    explanation: "F − f = ma. fR = Iα = (mR²/2)·(a/R) → f = ma/2. Подставляем: F − ma/2 = ma → a = 2F/(3m). f = ma/2 = F/3.",
  },
  {
    id: "phys-a-009",
    title: "Колебательный контур с резистором",
    description: "Конденсатор C заряжен до U0 и замкнут на катушку L. Когда Wэ = Wм, в контур последовательно включают резистор R. Найдите максимум теплоты на резисторе после этого момента.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "CU₀²/4",
    explanation: "Wэ = Wм = CU₀²/4 в момент включения. После включения R — затухающие колебания, вся энергия выделяется на R. Q = CU₀²/4 + оставшаяся энергия. Максимум теплоты = CU₀²/2 (при полном затухании).",
  },
  {
    id: "phys-a-010",
    title: "Две линзы",
    description: "Две одинаковые собирающие линзы с фокусным расстоянием f расположены на оси на расстоянии 3f друг от друга. Предмет на расстоянии 1,5f перед первой линзой. Найдите положение оконччного изображения и продольное увеличение.",
    subject: "physics",
    difficulty: "hard",
    type: "text",
    correctAnswer: "-image on left of 2nd lens, distance f, M = -2",
    explanation: "1-я линза: 1/v1 = 1/f − 1/(1,5f) = 1/(3f) → v1 = 3f. Изображение совпадает с 2-й линзой, расстояние между линзами = 3f. Объект для 2-й линзы: u2 = 0. 1/v2 = 1/f → v2 = f (за линзой). Увеличение: m = m1·m2 = (−2)·(−1) = 2.",
  },
]

const cf = (c: number, i: string, t: string): ExternalProblem => ({
  id: `cf-${c}${i}`,
  platform: "codeforces",
  externalId: `${c}/${i}`,
  title: t,
  subject: "informatics",
  difficulty: "easy",
  url: `https://codeforces.com/problemset/problem/${c}/${i}`,
})

export const externalProblemsData: ExternalProblem[] = [
  cf(1, "A", "Theatre Square"),
  cf(4, "A", "Watermelon"),
  cf(41, "A", "Translation"),
  cf(50, "A", "Domino piling"),
  cf(58, "A", "Chat room"),
  cf(59, "A", "Word"),
  cf(61, "A", "Ultra-Fast Mathematician"),
  cf(69, "A", "Young Physicist"),
  cf(71, "A", "Way Too Long Words"),
  cf(80, "A", "Panoramix's Prediction"),
  cf(96, "A", "Football"),
  cf(112, "A", "Petya and Strings"),
  cf(116, "A", "Tram"),
  cf(118, "A", "String Task"),
  cf(133, "A", "HQ9+"),
  cf(151, "A", "Soft Drinking"),
  cf(158, "A", "Next Round"),
  cf(160, "A", "Twins"),
  cf(200, "B", "Drinks"),
  cf(228, "A", "Is your horseshoe on the other hoof?"),
  cf(231, "A", "Team"),
  cf(236, "A", "Boy or Girl"),
  cf(263, "A", "Beautiful Matrix"),
  cf(271, "A", "Beautiful Year"),
  cf(281, "A", "Word Capitalization"),
  cf(282, "A", "Bit++"),
  cf(318, "A", "Even Odds"),
  cf(339, "A", "Helpful Maths"),
  cf(405, "A", "Gravity Flip"),
  cf(467, "A", "George and Accommodation"),
  cf(469, "A", "I Wanna Be the Guy"),
  cf(479, "A", "Expression"),
  cf(486, "A", "Calculating Function"),
  cf(546, "A", "Soldier and Bananas"),
  cf(617, "A", "Elephant"),
  cf(677, "A", "Vanya and Fence"),
  cf(703, "A", "Mishka and Game"),
  cf(705, "A", "Hulk"),
  cf(734, "A", "Anton and Danik"),
  cf(785, "A", "Anton and Polyhedrons"),
  cf(791, "A", "Bear and Big Brother"),
  cf(977, "A", "Wrong Subtraction"),
  cf(1030, "A", "In Search of an Easy Problem"),
  cf(1669, "A", "Division?"),
  cf(1703, "A", "YES or YES?"),
  cf(1772, "A", "A+B?"),
  cf(1807, "A", "Plus or Minus"),
  cf(1829, "A", "Love Story"),
  cf(1915, "A", "Odd One Out"),
  cf(1950, "A", "Stair, Peak, or Neither?"),
  cf(1971, "A", "My First Sorting Problem"),
  cf(1999, "A", "A+B Again?"),
  cf(2010, "B", "Three Brothers"),
  cf(2052, "M", "Managing Cluster"),
  cf(2167, "A", "Square?"),
  cf(2167, "B", "Your Name"),
  cf(2185, "B", "Prefix Max"),
]
